version: '3'

services:
  db:
    build: .
    container_name: mssqlbkp
    working_dir : /var/opt/mssql
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: PWD@1234
    ports:
      - 1410:1433
    volumes :
      - ./scripts:/var/opt/mssql/scripts
      - /Users/mbp_principal/bkp:/var/opt/mssql/bkp
  #command: ["/bin/bash", "/var/opt/mssql/scripts/Actions.sh", "start"]